


--DECLARE COMMON TABLE EXPRESSION TO RANK QCEW ENTRIES BY MOST RECENT REPORT AND HIGHEST TOTAL WAGES FOR DEDUPLICATING EMPLOYER RECORDS
WITH QCEW_EMPLOYERS_RANKED AS (
	SELECT
	QCEW.EIN,
	Q.Quarter_ID,
	I.NAICS_National_Industry_ID,
	C.County_ID,
	
	CASE WHEN QCEW.MEEI_Code IN (1,2,3) THEN 'N'
		WHEN QCEW.MEEI_Code IN (4,5,6) THEN 'Y'
		ELSE NULL END
	AS Multiple_Worksite_Record,
	
	QCEW.QCEW_ID,
	QCEW.Total_Wages AS Total_Wages,

	ROW_NUMBER ( )   
	    OVER (PARTITION BY 	QCEW.EIN ORDER BY Q.Quarter_ID DESC, QCEW.Total_Wages DESC) --MOST RECENT THEN HIGHEST WAGES
	AS ROW
	    
	FROM
	ds_ar_dws.dbo.qcew QCEW
	JOIN tr_ar_2022.dbo.AR_RDIM_NAICS_National_Industry I ON (I.NAICS_National_Industry_Code=QCEW.NAICS_Code)
	JOIN tr_ar_2022.dbo.AR_RDIM_County C ON (C.County_Code= QCEW.State_FIPS+QCEW.County_Code)
	JOIN tr_ar_2022.dbo.AR_RDIM_Quarter Q ON (Q.Calendar_Year=QCEW.Reference_Year) AND (Q.Calendar_Quarter=QCEW.Reference_Quarter)
	
	WHERE 
	QCEW.Total_Wages > 0
	AND QCEW.EIN IS NOT NULL
),

--DECLARE COMMON TABLE EXPRESSION TO SURVIVE QCEW ENTRIES BY MOST RECENT REPORT AND HIGHEST TOTAL WAGES FOR DEDUPLICATING EMPLOYER RECORDS
QCEW_EMPLOYERS_SURVIVED AS (
SELECT 
QER.EIN,
QER.Quarter_ID,
QER.NAICS_National_Industry_ID,
QER.County_ID,
QER.Multiple_Worksite_Record

FROM
QCEW_EMPLOYERS_RANKED QER
WHERE
QER.ROW = 1
)


--LOAD EMPLOYER MASTER DIMENSION WITH UNIQUE EMPLOYER IDENTITIES AND SURVIVED QCEW ATTRIBUTES

INSERT INTO tr_ar_2022.dbo.AR_MDIM_Employer (
	Federal_EIN,
	State_EIN,
	NAICS_National_Industry_ID,
	County_ID,
	Multiple_Worksite_Record
)
SELECT DISTINCT 
UIWL.Federal_EIN,
UIWL.State_EIN,
QCEW.NAICS_National_Industry_ID,
QCEW.County_ID,
QCEW.Multiple_Worksite_Record
FROM 
ds_ar_dws.dbo.ui_wages_lehd UIWL
LEFT JOIN QCEW_EMPLOYERS_SURVIVED QCEW ON (UIWL.Federal_EIN=QCEW.EIN)

 --DISTINCT EMPLOYERS: REDACTED
 --FEDERAL EIN: REDACTED












